# 감성분석 Sentiment Analysis

### 데이터 전처리

In [1]:
import codecs # 인코딩 변환 시켜주는 method
def read_data(filename):
    with codecs.open(filename, encoding='utf-8', mode='r') as f:
        data = [line.split('\t') for line in f.read().splitlines()]
        data = data[1:]
    return data

train_data = read_data('/home/dockeruser/data/nsmc/ratings_train.txt')
test_data = read_data('/home/dockeruser/data/nsmc/ratings_test.txt')

In [2]:
X = zip(*train_data)[1]
y = zip(*train_data)[2]
y = np.array(y, dtype=int)

In [18]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=10000, test_size=10000)
len(X_train), len(X_test)

(10000, 10000)

In [12]:
print(X[0:1])

(u'\uc544 \ub354\ube59.. \uc9c4\uc9dc \uc9dc\uc99d\ub098\ub124\uc694 \ubaa9\uc18c\ub9ac',)


In [19]:
from konlpy.utils import pprint # 한글 출력시 문제 해결하는 method
pprint((X[0:10], y[0:10]))

((아 더빙.. 진짜 짜증나네요 목소리,
  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나,
  너무재밓었다그래서보는것을추천한다,
  교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정,
  사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 던스트가 너무나도 이뻐보였다,
  막 걸음마 뗀 3세부터 초등학교 1학년생인 8살용영화.ㅋㅋㅋ...별반개도 아까움.,
  원작의 긴장감을 제대로 살려내지못했다.,
  별 반개도 아깝다 욕나온다 이응경 길용우 연기생활이몇년인지..정말 발로해도 그것보단 낫겟다 납치.감금만반복반복..이드라마는 가족도없다 연기못하는사람만모엿네,
  액션이 없는데도 재미 있는 몇안되는 영화,
  왜케 평점이 낮은건데? 꽤 볼만한데.. 헐리우드식 화려함에만 너무 길들여져 있나?),
 array([0, 1, 0, 0, 1, 0, 0, 0, 1, 1]))


In [20]:
# CountVectorize 사용

In [25]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, confusion_matrix


clf_1 = Pipeline([
            ('vect', CountVectorizer()), 
            ('clf', MultinomialNB()),
        ])

In [30]:
clf_1.fit(X_train, y_train)

Pipeline(steps=[('vect', CountVectorizer(analyzer=u'word', binary=False, decode_error=u'strict',
        dtype=<type 'numpy.int64'>, encoding=u'utf-8', input=u'content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern=u'(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)), ('clf', MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))])

In [24]:
pprint(list(clf_1.named_steps["vect"].vocabulary_)[:10])

[당당해,
 죠스,
 chthonic,
 죽어가는,
 초석은,
 앞으론,
 너무아름다웠던,
 도입부,
 23년전에,
 이야기끌고가는게]


In [33]:
pprint(y_test[:10])

array([0, 0, 1, 1, 0, 1, 0, 0, 0, 1])


In [34]:
pprint(clf_1.predict(X_test)[:10])

array([1, 1, 1, 1, 0, 1, 1, 0, 1, 1])


In [32]:
print(confusion_matrix(y_test[:10], clf_1.predict(X_test)[:10]))

[[2 4]
 [0 4]]


In [36]:
pprint(y_train[:10])

array([0, 0, 0, 1, 1, 1, 0, 1, 0, 0])


In [37]:
pprint(clf_1.predict(X_train)[:10])

array([0, 0, 0, 1, 1, 1, 0, 1, 0, 0])


In [35]:
print(confusion_matrix(y_train[:10], clf_1.predict(X_train)[:10]))

[[6 0]
 [0 4]]


In [40]:
pprint(X_test[:10])

[국내 개봉하기도 전에 봤었는데.. 당시 기준에선 몇몇 볼만한 칼질씬은 있었다,
 이처럼 조잡한 충동에 최고의 상을 부여함으로써 칸느가 자신들의 수준조차 밑돌았던 이유는 편견의 힘. 카메라의 시선은 알량하고 오만한데 이란 민중에 대한 희롱을 넘어 인간에 대한 모욕. 이런 역겨운 토사물에 꼬인 파리떼의 성찬은 당연한 결과,
 이야!! 재밋다!! 하하하!! . . .,
 다시 보니 수작이란걸 알게 되었습니다. 이런 영화를 평가절하했던 몇년전 어린 저에게 반성을 조금 나이먹고 보니 오히려 맨오브스틸보다 더 잘만든영화였단걸 깨닫게 되었네요 ㅜㅜ 아 차라리 이 시리즈의 후속편을 만들지,
 리뷰가 너무 웃겨서 방금 다운받으려다 말았..ㅋㅋ,
 8점은 되야된다고 생각해서 10점줌 ㅋㅋㅋ 배우들도 아는 배우들이 보이니까 더 재밋엇네요 ㅋㅋ,
 정말 재미없고도 어슬프게 재미있었다.,
 마지막까지 답답한 영화. 아빠가 목졸려 죽을 것 같은 상황에 경찰이 왔으면 잽싸게 달려나가 문을 열어줘야지ㅋㅋㅋ 답답하고 어설픈 안 보는게 이득인 쓰레기 영화.,
 cg다시보고싶다,
 소재가 아름다운 영화. 다소 아쉬운 부분들이 있는 이유는 이 영화는 영화스러운 극적 로맨스보단, 좀 더 사실적으로 한 남자의 마음과 시선을 말하고 싶었기 때문 아닐까.]


In [42]:
y_test[:10]

array([0, 0, 1, 1, 0, 1, 0, 0, 0, 1])

In [41]:
clf_1.predict(X_test[:10])

array([1, 1, 1, 1, 0, 1, 1, 0, 1, 1])

In [47]:
print(classification_report(y_test, clf_1.predict(X_test)))

             precision    recall  f1-score   support

          0       0.83      0.69      0.75      5014
          1       0.73      0.86      0.79      4986

avg / total       0.78      0.77      0.77     10000



In [43]:
# TfidVectorizer 사용

In [44]:
from sklearn.feature_extraction.text import TfidfVectorizer

clf_2 = Pipeline([
            ('vect', TfidfVectorizer()), 
            ('clf', MultinomialNB()),
        ])

In [45]:
clf_2.fit(X_train, y_train)

Pipeline(steps=[('vect', TfidfVectorizer(analyzer=u'word', binary=False, decode_error=u'strict',
        dtype=<type 'numpy.int64'>, encoding=u'utf-8', input=u'content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm=u'l2', preprocessor=None, smooth_idf=True...rue,
        vocabulary=None)), ('clf', MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))])

In [46]:
print(classification_report(y_test, clf_2.predict(X_test)))

             precision    recall  f1-score   support

          0       0.83      0.69      0.75      5014
          1       0.73      0.86      0.79      4986

avg / total       0.78      0.77      0.77     10000



In [48]:
# 형태소 분석기 사용

In [53]:
from konlpy.tag import Twitter
pos_tagger = Twitter()

def tokenize_pos(doc):
    return ['/'.join(t) for t in pos_tagger.pos(doc, norm=True, stem=True)]

clf_3 = Pipeline([
            ('vect', CountVectorizer(tokenizer=tokenize_pos)), 
            ('clf', MultinomialNB()),
        ])

In [54]:
clf_3.fit(X_train, y_train)

Pipeline(steps=[('vect', CountVectorizer(analyzer=u'word', binary=False, decode_error=u'strict',
        dtype=<type 'numpy.int64'>, encoding=u'utf-8', input=u'content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        st...d8>,
        vocabulary=None)), ('clf', MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))])

In [55]:
pprint(list(clf_3.named_steps["vect"].vocabulary_)[:10])

[찮음/Noun,
 자막/Noun,
 고래/Noun,
 괴벨스/Noun,
 강간/Noun,
 치료/Noun,
 꽉/Noun,
 계속계속/Adverb,
 믿다/Verb,
 슈나이더/Noun]


In [56]:
print(classification_report(y_test, clf_3.predict(X_test)))

             precision    recall  f1-score   support

          0       0.83      0.83      0.83      5014
          1       0.83      0.82      0.83      4986

avg / total       0.83      0.83      0.83     10000

